### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by thebookofjedediah** [thebookofjedediah/react-bulletin#12]
Next page/ new pages of items to render on command. Probably a feature with WP GraphQL that will allow a button to click next for more rendering

**Comment by lancebendo** [comment]
I'll give this a shot.

**Comment by thebookofjedediah** [comment]
This has been completed by Nemanja here: https://github.com/Nemanja629/infinite_scroll_blog_react

Just need to add it and style now
