### ISSUE TITLE
Create a Take-Action logic for time-sensitive posts

### ISSUE THREAD

**Issue by thebookofjedediah** [thebookofjedediah/react-bulletin#16]

**Comment by thebookofjedediah** [comment]
I want this to be something in drawer where; 
`if(data.categories.edges == "Time Sensitive" {display: none}`

**Comment by thebookofjedediah** [comment]
Same thing in the PostPreview and wherever else it renders the category name - this way when I hit "Take Action" it can render the category "Time Sensitive" without showing that category

**Comment by pantharshit00** [comment]
I don't understand this one. You are already filtering out time-sensitive posts.

**Comment by pantharshit00** [comment]
This seems already implemented via this button

![image](https://user-images.githubusercontent.com/22195362/61582748-5432f280-ab4c-11e9-8cdf-9da3008e8b27.png)
