### ISSUE TITLE
Mobile navbar not working in reality but is on chrome devtools

### ISSUE THREAD

**Issue by thebookofjedediah** [thebookofjedediah/react-bulletin#28]

**Comment by thebookofjedediah** [comment]
Need to update this so that in mobile view the gridView and the Printview Icons go away - maybe the search too if it can't fit with "Student Bulletin"

**Comment by pantharshit00** [comment]
In my testing on my Galaxy S10+, it works. Post some screenshots if it is not working.

**Comment by thebookofjedediah** [comment]
https://i.imgur.com/yeWVmaO.png

So I want the "GridView" and "Printview" to go away on mobile - so that the whole "Student Bulletin" words show up when on mobile. If the search has to go away also can you make an option for both since I don't know what I will like better?

**Comment by thebookofjedediah** [comment]
<img width="429" alt="Screen Shot 2019-07-20 at 1 04 13 PM" src="https://user-images.githubusercontent.com/37187167/61581753-3f287600-aaf0-11e9-8e21-191921197f37.png">

Easier screenshot

**Comment by pantharshit00** [comment]
Got it
